"""
Problem 2:

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1
and 2, the first  terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.. 

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""


def problem2_brute_force():
    """
    Brute force solution you can find all fibanacci numbers below 4,000,000 and add them to a running sum
    if they are even.
    """

    sum = 0

    curr = 2
    last = 1

    while curr < 4000000:
        # add the number if it is even
        if curr % 2 == 0:
            sum += curr

        # get the next fibonaci number 
        tmp = curr
        curr = next_fib(curr, last)
        last = tmp

    return sum


def next_fib(one, two):
    return one + two


def problem2():
    """
        fibonacci sequences follow the pattern of odd, odd, even. So we can represent this as a simpler series
        with 1/3 the number of terms as such ∑(n) = 4 * ∑(n-1) + ∑(n-2) 
    """

    # We can start from the 3rd even number to properly setup our last two
    curr = 8
    last = 2
    sum = 2

    while curr < 4000000:
        sum += curr
        tmp = curr
        curr = next_even_fib(curr, last)
        last = tmp

    return sum

def next_even_fib(last, last_last):
    return (4 * last) + last_last


print(problem2())